// @ts-nocheck

loc = [
  { localName: "서울특별시", engName: "Seoul Special City", korName: "서울특별시", xTile: "495", yTile: "517" },
  {
    localName: "인천광역시",
    engName: "Incheon Metropolitan City",
    korName: "인천광역시",
    xTile: "475.5",
    yTile: "508.5",
  },
  {
    localName: "대구광역시",
    engName: "Daegu Metropolitan City",
    korName: "대구광역시",
    xTile: "598.5",
    yTile: "398.5",
  },
  {
    localName: "대전광역시",
    engName: "Daejeon Metropolitan City",
    korName: "대전광역시",
    xTile: "519.5",
    yTile: "430.5",
  },
  {
    localName: "광주광역시",
    engName: "Gwangju Metropolitan City",
    korName: "광주광역시",
    xTile: "477.5",
    yTile: "351.5",
  },
  {
    localName: "부산광역시",
    engName: "Busan Metropolitan City",
    korName: "부산광역시",
    xTile: "637.5",
    yTile: "356.5",
  },
  {
    localName: "울산광역시",
    engName: "Ulsan Metropolitan City",
    korName: "울산광역시",
    xTile: "648.5",
    yTile: "378.5",
  },
  {
    localName: "세종특별자치시",
    engName: "Sejong Special Self-Governing City",
    korName: "세종특별자치시",
    xTile: "511",
    yTile: "447",
  },
  {
    localName: "수원시",
    engName: "Suwon City",
    korName: "수원시",
    xTile: "494.5",
    yTile: "495.5",
    provinceName: "경기도",
  },
  {
    localName: "청주시",
    engName: "Cheongju City",
    korName: "청주시",
    xTile: "527.5",
    yTile: "459.5",
    provinceName: "충청북도",
  },
  {
    localName: "홍성군",
    engName: "Hongseong County",
    korName: "홍성군",
    xTile: "470.5",
    yTile: "447.5",
    provinceName: "충청남도",
  },
  {
    localName: "전주시",
    engName: "Jeonju City",
    korName: "전주시",
    xTile: "508.5",
    yTile: "397.5",
    provinceName: "전라북도",
  },
  {
    localName: "무안군",
    engName: "Muan County",
    korName: "무안군",
    xTile: "464.5",
    yTile: "342.5",
    provinceName: "전라남도",
  },
  {
    localName: "안동시",
    engName: "Andong City",
    korName: "안동시",
    xTile: "611.5",
    yTile: "447.5",
    provinceName: "경상북도",
  },
  {
    localName: "창원시",
    engName: "Changwon City",
    korName: "창원시",
    xTile: "603.5",
    yTile: "354.5",
    provinceName: "경상남도",
  },
  {
    localName: "춘천시",
    engName: "Chuncheon City",
    korName: "춘천시",
    xTile: "544.5",
    yTile: "539.5",
    provinceName: "강원특별자치도",
  },
  {
    localName: "제주시",
    engName: "Jeju City",
    korName: "제주시",
    xTile: "459.5",
    yTile: "235.5",
    provinceName: "제주특별자치도",
  },
  { localName: "평양시", engName: "Pyongyang City", korName: "평양직할시", xTile: "397", yTile: "625" },
  { localName: "남포시", engName: "Nampho City", korName: "남포특별시", xTile: "380.5", yTile: "597.5" },
  { localName: "개성시", engName: "Kaesŏng City", korName: "개성특별시", xTile: "466.5", yTile: "541.5" },
  { localName: "라선시", engName: "Rasŏn City", korName: "라선특별시", xTile: "720.5", yTile: "835.5" },
  {
    localName: "함흥시",
    engName: "Hamhŭng City",
    korName: "함흥시",
    xTile: "534.5",
    yTile: "679.5",
    provinceName: "함경남도",
  },
  {
    localName: "청진시",
    engName: "Chŏngjin City",
    korName: "청진시",
    xTile: "681.5",
    yTile: "803.5",
    provinceName: "함경북도",
  },
  {
    localName: "혜산시",
    engName: "Hyesan City",
    korName: "혜산시",
    xTile: "580",
    yTile: "772",
    provinceName: "량강도",
  },
  {
    localName: "평성시",
    engName: "Phyŏngsŏng City",
    korName: "평성시",
    xTile: "408.5",
    yTile: "635.5",
    provinceName: "평안남도",
  },
  {
    localName: "신의주시",
    engName: "Sinŭiju City",
    korName: "신의주시",
    xTile: "324.5",
    yTile: "688.5",
    provinceName: "평안북도",
  },
  {
    localName: "강계시",
    engName: "Kanggye City",
    korName: "강계시",
    xTile: "467",
    yTile: "746",
    provinceName: "자강도",
  },
  {
    localName: "해주시",
    engName: "Haeju City",
    korName: "해주시",
    xTile: "404.5",
    yTile: "546.5",
    provinceName: "황해남도",
  },
  {
    localName: "사리원시",
    engName: "Sariwŏn City",
    korName: "사리원시",
    xTile: "403.5",
    yTile: "580.5",
    provinceName: "황해북도",
  },
  {
    localName: "원산시",
    engName: "Wŏnsan City",
    korName: "원산시",
    xTile: "516.5",
    yTile: "622",
    provinceName: "강원도",
  },
  {
    localName: "沈阳市",
    engName: "Shenyang City",
    korName: "선양시",
    xTile: "248.5",
    yTile: "799.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "大连市",
    engName: "Dalian City",
    korName: "다롄시",
    xTile: "128.5",
    yTile: "604.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "鞍山市",
    engName: "Anshan City",
    korName: "안산시",
    xTile: "221.5",
    yTile: "762.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "抚顺市",
    engName: "Fushun City",
    korName: "푸순시",
    xTile: "288.5",
    yTile: "800.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "本溪市",
    engName: "Benxi City",
    korName: "번시시",
    xTile: "273.5",
    yTile: "774.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "丹东市",
    engName: "Dandong City",
    korName: "단둥시",
    xTile: "313.5",
    yTile: "683.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "锦州市",
    engName: "Jinzhou City",
    korName: "진저우시",
    xTile: "99.5",
    yTile: "759.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "营口市",
    engName: "Yingkou City",
    korName: "잉커우시",
    xTile: "175.5",
    yTile: "723.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "阜新市",
    engName: "Fuxin City",
    korName: "푸신시",
    xTile: "139.5",
    yTile: "822.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "辽阳市",
    engName: "Liaoyang City",
    korName: "랴오양시",
    xTile: "235.5",
    yTile: "772.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "盘锦市",
    engName: "Panjin City",
    korName: "판진시",
    xTile: "168.5",
    yTile: "761.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "铁岭市",
    engName: "Tieling City",
    korName: "톄링시",
    xTile: "280.5",
    yTile: "837.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "朝阳市",
    engName: "Chaoyang City",
    korName: "차오양시",
    xTile: "51.5",
    yTile: "788.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "葫芦岛市",
    engName: "Huludao City",
    korName: "후루다오시",
    xTile: "72.5",
    yTile: "728.5",
    provinceName: "랴오닝성",
  },
  {
    localName: "兴安盟",
    engName: "Hinggan League",
    korName: "싱안맹",
    xTile: "170.5",
    yTile: "1093.5",
    provinceName: "내몽골자치주",
  },
  {
    localName: "通辽市",
    engName: "Tongliao City",
    korName: "퉁랴오시",
    xTile: "176.5",
    yTile: "933.5",
    provinceName: "내몽골자치주",
  },
  {
    localName: "呼伦贝尔市",
    engName: "Hulunbuir City",
    korName: "후룬베이얼시",
    xTile: "2.5",
    yTile: "1311.5",
    provinceName: "내몽골자치주",
  },
  {
    localName: "长春市",
    engName: "Changchun City",
    korName: "창춘시",
    xTile: "352.5",
    yTile: "949.5",
    provinceName: "지린성",
  },
  {
    localName: "吉林市",
    engName: "Jilin City",
    korName: "지린시",
    xTile: "464.5",
    yTile: "950.5",
    provinceName: "지린성 ",
  },
  {
    localName: "四平市",
    engName: "Siping City",
    korName: "쓰핑시",
    xTile: "322.5",
    yTile: "895.5",
    provinceName: "지린성",
  },
  {
    localName: "辽源市",
    engName: "Liaoyuan City",
    korName: "랴오위안시",
    xTile: "367.5",
    yTile: "878.5",
    provinceName: "지린성",
  },
  {
    localName: "通化市",
    engName: "Tonghua City",
    korName: "퉁화시",
    xTile: "418",
    yTile: "801",
    provinceName: "지린성",
  },
  {
    localName: "白山市",
    engName: "Baishan City",
    korName: "바이산시",
    xTile: "455",
    yTile: "819",
    provinceName: "지린성",
  },
  {
    localName: "松原市",
    engName: "Songyuan City",
    korName: "쑹위안시",
    xTile: "342.5",
    yTile: "1030.5",
    provinceName: "지린성",
  },
  {
    localName: "白城市",
    engName: "Baicheng City",
    korName: "바이청시",
    xTile: "214.5",
    yTile: "1065.5",
    provinceName: "지린성",
  },
  {
    localName: "延边朝鲜族自治州",
    engName: "Yanbian Korean Autonomous Prefecture",
    korName: "연변 조선족 자치주",
    xTile: "665.5",
    yTile: "875.5",
    provinceName: "지린성",
  },
  {
    localName: "哈尔滨市",
    engName: "Harbin City",
    korName: "하얼빈시",
    xTile: "473.5",
    yTile: "1073.5",
    provinceName: "헤이룽장성",
  },
  {
    localName: "齐齐哈尔市",
    engName: "Qiqihar City",
    korName: "치치하얼시",
    xTile: "307.5",
    yTile: "1185.5",
    provinceName: "헤이룽장성",
  },
  {
    localName: "鸡西市",
    engName: "Jixi City",
    korName: "지시시",
    xTile: "761.5",
    yTile: "1037.5",
    provinceName: "헤이룽장성",
  },
  {
    localName: "鹤岗市",
    engName: "Hegang City",
    korName: "허강시",
    xTile: "719.5",
    yTile: "1184.5",
    provinceName: "헤이룽장성",
  },
  {
    localName: "双鸭山市",
    engName: "Shuangyashan City",
    korName: "솽야산시",
    xTile: "764.5",
    yTile: "1144.5",
    provinceName: "헤이룽장성",
  },
  {
    localName: "大庆市",
    engName: "Daqing City",
    korName: "다칭시",
    xTile: "362.5",
    yTile: "1146.5",
    provinceName: "헤이룽장성",
  },
  {
    localName: "伊春市",
    engName: "Yichun City",
    korName: "이춘시",
    xTile: "619.5",
    yTile: "1212.5",
    provinceName: "헤이룽장성",
  },
  {
    localName: "佳木斯市",
    engName: "Jiamusi City",
    korName: "자무쓰시",
    xTile: "720.5",
    yTile: "1146.5",
    provinceName: "헤이룽장성",
  },
  {
    localName: "七台河市",
    engName: "Qitaihe City",
    korName: "치타이허시",
    xTile: "762.5",
    yTile: "1075.5",
    provinceName: "헤이룽장성",
  },
  {
    localName: "牡丹江市",
    engName: "Mudanjiang City",
    korName: "무단장시",
    xTile: "670.5",
    yTile: "985.5",
    provinceName: "헤이룽장성",
  },
  {
    localName: "黑河市",
    engName: "Heihe City",
    korName: "헤이허시",
    xTile: "522.5",
    yTile: "1372.5",
    provinceName: "헤이룽장성",
  },
  {
    localName: "绥化市",
    engName: "Suihua City",
    korName: "쑤이화시",
    xTile: "488.5",
    yTile: "1145.5",
    provinceName: "헤이룽장성",
  },
  { localName: "上海市", engName: "Shanghai Municipality", korName: "상하이시", xTile: "120", yTile: "81" },
  {
    localName: "青岛市",
    engName: "Qingdao City",
    korName: "칭다오시",
    xTile: "42.5",
    yTile: "414.5",
    provinceName: "산둥성",
  },
  {
    localName: "烟台市",
    engName: "Yantai City",
    korName: "옌타이시",
    xTile: "113.5",
    yTile: "507.5",
    provinceName: "산둥성",
  },
  {
    localName: "威海市",
    engName: "Weihai City",
    korName: "웨이하이시",
    xTile: "159.5",
    yTile: "510.5",
    provinceName: "산둥성",
  },
  {
    localName: "无锡市",
    engName: "Wuxi City",
    korName: "우시시",
    xTile: "41.5",
    yTile: "104.5",
    provinceName: "장쑤성",
  },
  {
    localName: "常州市",
    engName: "Changzhou City",
    korName: "창저우시",
    xTile: "15.5",
    yTile: "129.5",
    provinceName: "장쑤성",
  },
  {
    localName: "苏州市",
    engName: "Suzhou City",
    korName: "쑤저우시",
    xTile: "60.5",
    yTile: "84.5",
    provinceName: "장쑤성",
  },
  {
    localName: "南通市",
    engName: "Nantong City",
    korName: "난퉁시",
    xTile: "77.5",
    yTile: "135.5",
    provinceName: "장쑤성",
  },
  {
    localName: "盐城市",
    engName: "Yancheng City",
    korName: "옌청시",
    xTile: "31.5",
    yTile: "230.5",
    provinceName: "장쑤성",
  },
  {
    localName: "泰州市",
    engName: "Taizhou City",
    korName: "타이저우시",
    xTile: "12.5",
    yTile: "165.5",
    provinceName: "장쑤성",
  },
  {
    localName: "杭州市",
    engName: "Hangzhou City",
    korName: "항저우시",
    xTile: "25.5",
    yTile: "19.5",
    provinceName: "저장성",
  },
  {
    localName: "宁波市",
    engName: "Ningbo City",
    korName: "닝보시",
    xTile: "111.5",
    yTile: "1.5",
    provinceName: "저장성",
  },
  {
    localName: "绍兴市",
    engName: "Shaoxing City",
    korName: "사오싱시",
    xTile: "56.5",
    yTile: "2.5",
    provinceName: "저장성",
  },
  {
    localName: "嘉兴市",
    engName: "Jiaxing City",
    korName: "자싱시",
    xTile: "67.5",
    yTile: "53.5",
    provinceName: "저장성",
  },
  {
    localName: "湖州市",
    engName: "Huzhou City",
    korName: "후저우시",
    xTile: "24.5",
    yTile: "63.5",
    provinceName: "저장성",
  },
  {
    localName: "舟山市",
    engName: "Zhoushan City",
    korName: "저우산시",
    xTile: "165.5",
    yTile: "2.5",
    provinceName: "저장성",
  },
  {
    localName: "Биробиджан",
    engName: "Birobidzhan",
    korName: "비로비잔",
    xTile: "900",
    yTile: "1276",
    provinceName: "유대인 자치주",
  },
  {
    localName: "Хабаровск",
    engName: "Khabarovsk",
    korName: "하바롭스크",
    xTile: "1049",
    yTile: "1259",
    provinceName: "하바롭스크 지방",
  },
  {
    localName: "Благовещенск",
    engName: "Blagoveshchensk",
    korName: "블라고베셴스크",
    xTile: "532",
    yTile: "1382",
    provinceName: "아무르주",
  },
  {
    localName: "Южно-Сахалинск",
    engName: "Yuzhno-Sakhalinsk",
    korName: "유즈노사할린스크",
    xTile: "1560",
    yTile: "1154",
    provinceName: "사할린주",
  },
  {
    localName: "Владивосток",
    engName: "Vladivostok",
    korName: "블라디보스토크",
    xTile: "829",
    yTile: "894",
    provinceName: "프리모리예 지방",
  },
  {
    localName: "東京都",
    engName: "Tokyo Metropolis",
    korName: "도쿄",
    xTile: "1362",
    yTile: "384",
    provinceName: "도쿄도",
  },
  {
    localName: "札幌市",
    engName: "Sapporo City",
    korName: "삿포로시",
    xTile: "1468.5",
    yTile: "890.5",
    provinceName: "훗카이도",
  },
  {
    localName: "京都市",
    engName: "Kyoto City",
    korName: "교토시",
    xTile: "1097.5",
    yTile: "340.5",
    provinceName: "교토부",
  },
  {
    localName: "大阪市",
    engName: "Osaka City",
    korName: "오사카시",
    xTile: "1073.5",
    yTile: "316.5",
    provinceName: "오사카부",
  },
  {
    localName: "青森市",
    engName: "Aomori City",
    korName: "아오모리시",
    xTile: "1427.5",
    yTile: "734.5",
    provinceName: "아오모리현",
  },
  {
    localName: "盛岡市",
    engName: "Morioka City",
    korName: "모리오카시",
    xTile: "1449.5",
    yTile: "659.5",
    provinceName: "이와테현",
  },
  {
    localName: "仙台市",
    engName: "Sendai City",
    korName: "센다이시",
    xTile: "1436.5",
    yTile: "562.5",
    provinceName: "미야기현",
  },
  {
    localName: "秋田市",
    engName: "Akita City",
    korName: "아키타시",
    xTile: "1383.5",
    yTile: "662.5",
    provinceName: "아키타현",
  },
  {
    localName: "山形市",
    engName: "Yamagata City",
    korName: "야마가타시",
    xTile: "1400.5",
    yTile: "563.5",
    provinceName: "야마가타현",
  },
  {
    localName: "福島市",
    engName: "Fukushima City",
    korName: "후쿠시마시",
    xTile: "1411.5",
    yTile: "528.5",
    provinceName: "후쿠시마현",
  },
  {
    localName: "水戸市",
    engName: "Mito City",
    korName: "미토시",
    xTile: "1413.5",
    yTile: "431.5",
    provinceName: "이바라키현",
  },
  {
    localName: "宇都宮市",
    engName: "Utsunomiya City",
    korName: "우쓰노미야시",
    xTile: "1373.5",
    yTile: "442.5",
    provinceName: "도치기현",
  },
  {
    localName: "前橋市",
    engName: "Maebashi City",
    korName: "마에바시시",
    xTile: "1318.5",
    yTile: "433.5",
    provinceName: "군마현",
  },
  {
    localName: "さいたま市",
    engName: "Saitama City",
    korName: "사이타마시",
    xTile: "1356.5",
    yTile: "399.5",
    provinceName: "사이타마현",
  },
  {
    localName: "千葉市",
    engName: "Chiba City",
    korName: "치바시",
    xTile: "1387.5",
    yTile: "383.5",
    provinceName: "치바현",
  },
  {
    localName: "横浜市",
    engName: "Yokohama City",
    korName: "요코하마시",
    xTile: "1352.5",
    yTile: "370.5",
    provinceName: "가나가와현",
  },
  {
    localName: "新潟市",
    engName: "Niigata City",
    korName: "니가타시",
    xTile: "1307.5",
    yTile: "502.5",
    provinceName: "니가타현",
  },
  {
    localName: "富山市",
    engName: "Toyama City",
    korName: "도야마시",
    xTile: "1191.5",
    yTile: "454.5",
    provinceName: "도야마현",
  },
  {
    localName: "金沢市",
    engName: "Kanazawa City",
    korName: "가나자와시",
    xTile: "1147.5",
    yTile: "444.5",
    provinceName: "이시카와현",
  },
  {
    localName: "福井市",
    engName: "Fukui City",
    korName: "후쿠이시",
    xTile: "1119.5",
    yTile: "410.5",
    provinceName: "후쿠이현",
  },
  {
    localName: "甲府市",
    engName: "Kofu City",
    korName: "고후시",
    xTile: "1282.5",
    yTile: "382.5",
    provinceName: "야마나시현",
  },
  {
    localName: "長野市",
    engName: "Nagano City",
    korName: "나가노시",
    xTile: "1258.5",
    yTile: "451.5",
    provinceName: "나가노현",
  },
  {
    localName: "岐阜市",
    engName: "Gifu City",
    korName: "기후시",
    xTile: "1161.5",
    yTile: "367.5",
    provinceName: "기후현",
  },
  {
    localName: "静岡市",
    engName: "Shizuoka City",
    korName: "시즈오카시",
    xTile: "1267.5",
    yTile: "337.5",
    provinceName: "시즈오카현",
  },
  {
    localName: "名古屋市",
    engName: "Nagoya City",
    korName: "나고야시",
    xTile: "1168.5",
    yTile: "356.5",
    provinceName: "아이치현",
  },
  { localName: "津市", engName: "Tsu City", korName: "쓰시", xTile: "1136.5", yTile: "321.5", provinceName: "미에현" },
  {
    localName: "大津市",
    engName: "Otsu City",
    korName: "오쓰시",
    xTile: "1101.5",
    yTile: "347.5",
    provinceName: "시가현",
  },
  {
    localName: "神戸市",
    engName: "Kobe City",
    korName: "고베시",
    xTile: "1050.5",
    yTile: "318.5",
    provinceName: "효고현",
  },
  {
    localName: "奈良市",
    engName: "Nara City",
    korName: "나라시",
    xTile: "1095.5",
    yTile: "314.5",
    provinceName: "나라현",
  },
  {
    localName: "和歌山市",
    engName: "Wakayama City",
    korName: "와카야마시",
    xTile: "1053.5",
    yTile: "286.5",
    provinceName: "와카야마현",
  },
  {
    localName: "鳥取市",
    engName: "Tottori City",
    korName: "돗토리시",
    xTile: "986.5",
    yTile: "374.5",
    provinceName: "돗토리현",
  },
  {
    localName: "松江市",
    engName: "Matsue City",
    korName: "마쓰에시",
    xTile: "906.5",
    yTile: "372.5",
    provinceName: "시마네현",
  },
  {
    localName: "岡山市",
    engName: "Okayama City",
    korName: "오카야마시",
    xTile: "964.5",
    yTile: "314.5",
    provinceName: "오카야마현",
  },
  {
    localName: "広島市",
    engName: "Hiroshima City",
    korName: "히로시마시",
    xTile: "865.5",
    yTile: "299.5",
    provinceName: "히로시마현",
  },
  {
    localName: "山口市",
    engName: "Yamaguchi City",
    korName: "야마구치시",
    xTile: "805.5",
    yTile: "285.5",
    provinceName: "야마구치현",
  },
  {
    localName: "徳島市",
    engName: "Tokushima City",
    korName: "도쿠시마시",
    xTile: "1005.5",
    yTile: "275.5",
    provinceName: "도쿠시마현",
  },
  {
    localName: "高松市",
    engName: "Takamatsu City",
    korName: "다카마쓰시",
    xTile: "971.5",
    yTile: "293.5",
    provinceName: "카가와현",
  },
  {
    localName: "松山市",
    engName: "Matsuyama City",
    korName: "마쓰야마시",
    xTile: "884.5",
    yTile: "258.5",
    provinceName: "에히메현",
  },
  {
    localName: "高知市",
    engName: "Kōchi City",
    korName: "고치시",
    xTile: "936.5",
    yTile: "240.5",
    provinceName: "고치현",
  },
  {
    localName: "福岡市",
    engName: "Fukuoka City",
    korName: "후쿠오카시",
    xTile: "722.5",
    yTile: "241.5",
    provinceName: "후쿠오카현",
  },
  {
    localName: "佐賀市",
    engName: "Saga City",
    korName: "사가시",
    xTile: "716.5",
    yTile: "221.5",
    provinceName: "사가현",
  },
  {
    localName: "長崎市",
    engName: "Nagasaki City",
    korName: "나가사키시",
    xTile: "689.5",
    yTile: "184.5",
    provinceName: "나가사키현",
  },
  {
    localName: "熊本市",
    engName: "Kumamoto City",
    korName: "구마모토시",
    xTile: "746.5",
    yTile: "187.5",
    provinceName: "구마모토현",
  },
  {
    localName: "大分市",
    engName: "Oita City",
    korName: "오이타시",
    xTile: "804.5",
    yTile: "218.5",
    provinceName: "오이타현",
  },
  {
    localName: "宮崎市",
    engName: "Miyazaki City",
    korName: "미야자키시",
    xTile: "791.5",
    yTile: "130.5",
    provinceName: "미야자키현",
  },
  {
    localName: "鹿児島市",
    engName: "Kagoshima City",
    korName: "가고시마시",
    xTile: "733.5",
    yTile: "106.5",
    provinceName: "가고시마현",
  },
];
objective = Reflect.get(Reflect.get(Vars.ui.editor, "infoDialog"), "objectives").canvas.objectives.get(0);

for (var l of loc) {
  var marker = new MapObjectives.TextMarker(
    "[accent]" + l.localName + "[]\n" + l.engName + "\n[lightgray]" + l.korName + "[]",
    l.xTile * 8,
    l.yTile * 8 + 8
  );
  marker.fontSize = 1.5;
  objective.markers = Structs.add(objective.markers, marker);
}
